apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  description: Dev environment

  sourceRepos:
    - https://github.com/gchie/demo-api
    - https://github.com/gchie/demo-web

  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
