apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev 
  namespace: argocd
spec:
  description: Development environment 

  sourceRepos:
    - https://github.com/gchie/platform-gitops
  
  destination:
    - namespace: dev 
      server: 'https://kubernetes.default.svc'
    
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'