apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api-test
  namespace: argocd
spec:
  project: test

  source:
    repoURL: https://github.com/gchie/demo-api
    targetRevision: main
    path: helm/demo-api
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
